development:
  host: dev.example.com
  email: john@doe.net
  password: apassword
  # api_key: <your api key here>
staging:
  host: http://localhost:8080
  email: garrett.roach@gmail.com
  password: password
  api_key: a3e94c9b9830224179d0e89f4c36b7d2e050828a
production:
  host: www.example.com
  email: john@doe.net
  password: apassword
  # api_key: <your api key here>